config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :comments
  end

  get    '/:id'    => 'posts#individual', as: "individual"

  root 'posts#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end
  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  private
  def comment_params
    params.require(:comment).permit(:reply)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def home
    @users = User.all
  end
  def individual
    @user = User.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :reply %>
  <%= f.text_field :reply %>

  <%= f.submit %>
<% end %>
<p><%= link_to "Cancel", posts_path %></p>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>
<%= render "form" %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h2>New Comment</h2>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grubbable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="">
      <% if !current_user %>
        <%= link_to "Sign up", new_user_registration_path %>
        <%= link_to "Sign in", new_user_session_path %>
      <% else %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <%= current_user.email %>
      <% end %>
    </div>
    <div >
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <div id="new"><%= yield %></div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>
<p><%= link_to "Cancel", posts_path %></p>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render "form" %>

app/views/posts/home.html.erb
<%= link_to "Edit User Information",edit_user_registration_path%>
<%=current_user.first_name%>

<p>Click <%= link_to "here",posts_path%> to see all posts</p>

<h2>Friends</h2>
<% @users.each do |user| %>
<span>
  <img width="30px" src="http://ornithology.ucc.ie/wp-content/uploads/sites/41/2015/10/Unknown-person.gif" alt="photo">
  <%= link_to user.email, individual_path(user.id) %>
</span>
<% end %>

app/views/posts/index.html.erb
<%= link_to "Back", :root %>

<h1>All posts by all users</h1>

<%= link_to "New",new_post_path%>

<% @posts.each do |post|%>
  <p><%= link_to post.title, post_path(post)%></p>
<%end%>

app/views/posts/individual.html.erb
<%= link_to "Back", :root %>
<h1>Post by   <%= @user.first_name %> </h1>


<% @user.posts.each do |post|%>
  <h3><%= post.title%>: <%= post.body%></h3>
  <p>
    <% post.comments.each do |comment|%>
      <%= comment.reply%>  
    <%end%>
  </p>
<%end%>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<%= link_to "Edit Post", edit_post_path(@post) %>
<%= link_to "Delete Post", post_path(@post), method: :delete %>
<%= link_to "Back", posts_path %>
<h1>Title: <%= @post.title%></h1>
<h2>Body: <%= @post.body%></h2>
<h2>By: <%= @post.user.first_name%></h2>


<%= link_to "Add new comment", new_post_comment_path(@post) %>

<% @post.comments.each do |comment| %>
  <p>	<%= comment.reply %>
    <%= link_to "Edit", edit_post_comment_path(@post, comment) %> |
    <%= link_to "Delete", post_comment_path(@post, comment), method: :delete %>
  </p>
<% end %>